fix: fixed security-bootstrapper Docker volume init semantics
edgexfoundry/edgex-examples pull request #124
Opened 2022-07-07 18:18 UTC by vli11

fixes: #3851 remove WA
Signed-off-by: Valina Li <valina.li@intel.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)

## Testing Instructions

2022-07-07 18:48 UTC, jim-wang-intel commented on deployment/helm/templates/edgex-security-bootstrapper/edgex-security-bootstrapper-deployment.yaml
> -      initContainers:
yes, when we tested it we use this local image with others in 2.2.0; i.e. `security-bootstrapper` is local built docker image tag `0.0.0-dev` and others are pulling from `2.2.0` tag

2022-07-07 18:51 UTC, lenny-intel commented on deployment/helm/templates/edgex-security-bootstrapper/edgex-security-bootstrapper-deployment.yaml
> -      initContainers:
Ok, but this change doesn't change the bootstrapper image. Still uses 2.2.0.

2022-07-07 19:15 UTC, jim-wang-intel commented
**Hold** until we have correct docker image deployed in nexus

2022-07-20 16:31 UTC, bnevis-i commented
Unholding.  Please merge.

2022-07-25 14:48 UTC, bnevis-i requested changes

2022-07-25 14:48 UTC, bnevis-i commented on deployment/helm/values.yaml
> +      tag: "latest"
There is no "edgexfoundry/security-bootstrapper:latest" on Dockerhub.

Please change "respository" to point to the Nexus images.

See https://github.com/edgexfoundry/edgex-compose/blob/main/compose-builder/.env

2022-07-25 17:56 UTC, bnevis-i approved these changes
Tested. Works fine.

2022-07-25 17:57 UTC, merged