refactor: Upgrade cloud-export-mqtt to use V3
edgexfoundry/edgex-examples pull request #201
Opened 2023-05-11 00:08 UTC by marcpfuller

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)

## Testing Instructions
Start edgex with no-secty
run `./app-service -p aws -cp -o -dev`
verify service starts up
run `./app-service -p azure -cp -o -dev`
verify service starts up

2023-05-11 17:02 UTC, jim-wang-intel submitted a review, later dismissed
LGTM

2023-05-15 21:28 UTC, lenny-intel requested changes

2023-05-15 21:28 UTC, lenny-intel commented on application-services/custom/cloud-export-mqtt/res/aws/configuration.yaml
> +#Type="http"
Remove

2023-05-15 21:28 UTC, lenny-intel commented on application-services/custom/cloud-export-mqtt/res/aws/configuration.yaml
> +  PublishTopic: "example"  # Base topic is prepened to this topic when using edgex-messagebus
```suggestion
# Using default Trigger config from common config
```

2023-05-15 21:28 UTC, lenny-intel commented on application-services/custom/cloud-export-mqtt/res/azure/configuration.yaml
> +    PublishTopicPrefix : "edgex/telemetry" # /<service-name>/<metric-name> will be added to this Publish Topic prefix
```suggestion
```

2023-05-15 21:28 UTC, lenny-intel commented on application-services/custom/cloud-export-mqtt/res/azure/configuration.yaml
> +  PublishTopic: "example"  # Base topic is prepened to this topic when using edgex-messagebus
```suggestion
# Using default Trigger config from common config
```

2023-05-15 21:28 UTC, lenny-intel commented on application-services/custom/cloud-export-mqtt/res/azure/configuration.yaml
> +#Type:"http"
remove

2023-05-15 21:37 UTC, marcpfuller commented on application-services/custom/cloud-export-mqtt/res/azure/configuration.yaml
> +  PublishTopic: "example"  # Base topic is prepened to this topic when using edgex-messagebus
Done

2023-05-15 21:38 UTC, marcpfuller commented on application-services/custom/cloud-export-mqtt/res/azure/configuration.yaml
> +    PublishTopicPrefix : "edgex/telemetry" # /<service-name>/<metric-name> will be added to this Publish Topic prefix
Done

2023-05-15 21:38 UTC, marcpfuller commented on application-services/custom/cloud-export-mqtt/res/aws/configuration.yaml
> +  PublishTopic: "example"  # Base topic is prepened to this topic when using edgex-messagebus
Done

2023-05-15 21:38 UTC, marcpfuller commented on application-services/custom/cloud-export-mqtt/res/aws/configuration.yaml
> +#Type="http"
Done

2023-05-15 21:42 UTC, lenny-intel approved these changes
LGTM

2023-05-15 21:42 UTC, merged