refactor: Upgrade custom-trigger-nate-rpc to use V3
edgexfoundry/edgex-examples pull request #203
Opened 2023-05-11 00:52 UTC by marcpfuller

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)

## Testing Instructions
Start edgex with no-secty
run `./app-service  -cp -o -dev`
verify service starts up

2023-05-11 17:05 UTC, jim-wang-intel approved these changes

2023-05-15 21:23 UTC, lenny-intel requested changes

2023-05-15 21:23 UTC, lenny-intel commented on application-services/custom/custom-trigger-nats-rpc/res/configuration.yaml
> +    Interval: "0s" # Disabled since require MessageBus Trigger to be in use.
This needs to be applied to all PRs. 

```suggestion
    Interval: "0s" # Disabled, use non-zero duration to enable. MessageBus below must not be disable if Metrics are enabled,
```

2023-05-15 21:38 UTC, marcpfuller commented on application-services/custom/custom-trigger-nats-rpc/res/configuration.yaml
> +    Interval: "0s" # Disabled since require MessageBus Trigger to be in use.
Done

2023-05-15 21:40 UTC, lenny-intel approved these changes

2023-05-15 21:40 UTC, merged